### ISSUE TITLE
TLS1.3 Support

### ISSUE THREAD

**Issue by hpandroid** [iusrepo/haproxy20#6]
Hi, 
Can you please update the haproxy package to support TLS1.3 for CentOS 7.
Thanks

**Comment by carlwgeorge** [comment]
Thanks for the suggestion.  Unfortunately, this won't be possible.  HAProxy uses OpenSSL, and [TLS 1.3 wasn't added to OpenSSL until 1.1.1](https://wiki.openssl.org/index.php/TLS1.3).  RHEL and CentOS 7 only have 1.0.2k.  In the past [Red Hat has said that updating their EL7 package to 1.1.1 will not be possible](https://bugzilla.redhat.com/show_bug.cgi?id=1276310).  Due to a variety of reasons, [IUS is not interested in building an alternative version of OpenSSL](https://github.com/iusrepo/wishlist/issues/70).

If someone adds a parallel installable openssl package to EPEL, we can reevaluate this, but for now our hands are tied.

**Comment by prupert** [comment]
> If someone adds a parallel installable openssl package to EPEL, we can reevaluate this

openssl11 packages are actively maintained in EPEL7 for over a year now. Time to reevaluate? ;-)

**Comment by carlwgeorge** [comment]
Yes, openssl11 in EPEL should be an option, I'll take a look and see if I can get it to build.

**Comment by robert-scheck** [comment]
Most likely,

```
BuildRequires: openssl11-devel
```

and

```
export SSL_INC="$(pkg-config --cflags-only-I openssl11 | sed -e 's/^-I//')"
export SSL_LIB="$(pkg-config --libs-only-L openssl11 | sed -e 's/^-L//')"
```

should do the job for haproxy20, too.

**Comment by fraenki** [comment]
@carlwgeorge If it works for haproxy20, maybe you could to the same for haproxy22. There's also a request for TLS1.3: https://github.com/iusrepo/haproxy22/issues/9. Thanks :)

**Comment by prupert** [comment]
@carlwgeorge could you test with the adjustments of @robert-scheck against https://github.com/iusrepo/haproxy20/blob/main/haproxy20.spec

**Comment by jeffsheltren** [comment]
Added in #11
